services:
  - type: web
    name: vcsmusicbot-web
    env: python
    plan: free
    region: singapore
    branch: master

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      bash -c "python3 st.py & python3 -m http.server $PORT"

    autoDeploy: true
